from typing import Any, final, Self, Sequence, TypeAlias
from enum import Enum

from telethon._impl.session.types import PeerIdLike, PeerAuthLike

@final
class PeerId:
    __slots__ = ()

    def __new__(cls, id: PeerIdLike) -> Self: ...
    @staticmethod
    def self_user() -> PeerId: ...
    @staticmethod
    def user(id: int) -> PeerId: ...
    @staticmethod
    def chat(id: int) -> PeerId: ...
    @staticmethod
    def channel(id: int) -> PeerId: ...
    @property
    def kind(self) -> PeerKind:
        """
        Peer kind.
        """
        ...
    @property
    def bot_api_dialog_id(self) -> int:
        """
        Returns the identity using the Bot API Dialog ID format.

        Will return an arbitrary value if [`self.kind`] is [`PeerKind.UserSelf`].
        This value should not be relied on and may change between releases.
        """
        ...
    @property
    def bare_id(self) -> int:
        """
        Unpacked peer identifier. Panics if [`self.kind`] is [`PeerKind.UserSelf`].
        """
        ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: Any, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class PeerKind(Enum):
    """The peer identity belongs to a [`tl.types.User`]. May also represent [`PeerKind.UserSelf`]."""

    __slots__ = ()

    User = 0
    """The peer identity belongs to a user with its [`tl.types.User.is_self`] flag set to `true`."""
    UserSelf = 1
    """The peer identity belongs to a [`tl.types.Chat`] or one of its derivatives."""
    Chat = 2
    """The peer identity belongs to a [`tl.types.Channel`] or one of its derivatives."""
    Channel = 3

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: Any, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class PeerAuth:
    __slots__ = ()

    def __new__(cls, access_hash: int) -> Self: ...
    @property
    def hash(self) -> int: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: Any, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ChannelKind(Enum):
    """Value used for a channel with its [`tl.types.Channel.broadcast`] flag set to `true`."""

    __slots__ = ()

    Broadcast = 1
    """Value used for a channel with its [`tl.types.Channel.megagroup`] flag set to `true`."""
    Megagroup = 2
    """Value used for a channel with its [`tl.types.Channel.gigagroup`] flag set to `true`."""
    Gigagroup = 3

    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def __eq__(self, other: Any, /) -> bool: ...
    def __hash__(self) -> int: ...

class PeerInfo:
    __slots__ = ()

    @final
    class User(PeerInfo):
        __slots__ = ()

        def __new__(
            cls,
            id: int,
            auth: int | PeerAuth | None,
            bot: bool | None,
            is_self: bool | None,
        ) -> Self: ...
        @property
        def id(self) -> PeerId: ...
        @id.setter
        def id(self, id: PeerId) -> None: ...
        @property
        def auth(self) -> PeerAuth | None: ...
        @property
        def access_hash(self) -> PeerAuth | None: ...
        @property
        def bot(self) -> bool | None: ...
        @property
        def is_self(self) -> bool | None: ...

    @final
    class Chat(PeerInfo):
        __slots__ = ()

        def __new__(cls, id: int) -> Self: ...
        @property
        def id(self) -> PeerId: ...
        @id.setter
        def id(self, id: PeerId) -> None: ...
        @property
        def access_hash(self) -> None:
            return None

    @final
    class Channel(PeerInfo):
        __slots__ = ()

        def __new__(
            cls,
            id: int,
            auth: int | PeerAuth | None,
            kind: ChannelKind | None,
        ) -> Self: ...
        @property
        def id(self) -> PeerId: ...
        @id.setter
        def id(self, id: PeerId) -> None: ...
        @property
        def auth(self) -> PeerAuth: ...
        @property
        def access_hash(self) -> PeerAuth | None: ...
        @property
        def kind(self) -> ChannelKind: ...

    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Any, /) -> bool: ...

class PeerRef:
    __slots__ = ()

    def __new__(cls, id: PeerIdLike, auth: PeerAuthLike) -> Self: ...
    @property
    def id(self) -> PeerId: ...
    @id.setter
    def id(self, id: PeerIdLike) -> None: ...
    @property
    def auth(self) -> PeerAuth: ...
    @auth.setter
    def auth(self, auth: PeerAuthLike) -> None: ...
    @property
    def access_hash(self) -> PeerAuth: ...
    @property
    def kind(self) -> PeerKind: ...

@final
class DcOption:
    __slots__ = ()

    def __new__(
        cls,
        id: int,
        ipv4: str | None,
        ipv6: str | None,
        auth_key: bytes | None,
    ) -> Self: ...
    @property
    def id(self) -> int: ...
    @id.setter
    def id(self, id: int) -> None: ...
    @property
    def ipv4(self) -> SocketAddrV4: ...
    @ipv4.setter
    def ipv4(self, ipv4: SocketAddrV4) -> None: ...
    @property
    def ipv6(self) -> SocketAddrV6: ...
    @ipv6.setter
    def ipv6(self, ipv6: SocketAddrV6) -> None: ...
    @property
    def auth_key(self) -> bytes: ...
    @auth_key.setter
    def auth_key(self, auth_key: bytes) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Any, /) -> bool: ...

@final
class SocketAddrV4:
    __slots__ = ()

    def __new__(cls, ip: str | Sequence[int], port: int) -> Self: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, a: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, b: int) -> None: ...
    @property
    def c(self) -> int: ...
    @c.setter
    def c(self, c: int) -> None: ...
    @property
    def d(self) -> int: ...
    @d.setter
    def d(self, d: int) -> None: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, port: int) -> None: ...
    @property
    def ip(self) -> int: ...
    @ip.setter
    def ip(self, ip: int) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: Any, /) -> bool: ...

@final
class SocketAddrV6:
    __slots__ = ()

    def __new__(cls, ip: str | Sequence[int], port: int) -> Self: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, a: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, b: int) -> None: ...
    @property
    def c(self) -> int: ...
    @c.setter
    def c(self, c: int) -> None: ...
    @property
    def d(self) -> int: ...
    @d.setter
    def d(self, d: int) -> None: ...
    @property
    def e(self) -> int: ...
    @e.setter
    def e(self, e: int) -> None: ...
    @property
    def f(self) -> int: ...
    @f.setter
    def f(self, f: int) -> None: ...
    @property
    def g(self) -> int: ...
    @g.setter
    def g(self, g: int) -> None: ...
    @property
    def h(self) -> int: ...
    @h.setter
    def h(self, h: int) -> None: ...
    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, port: int) -> None: ...
    @property
    def ip(self) -> int: ...
    @ip.setter
    def ip(self, ip: int) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: Any, /) -> bool: ...

@final
class ChannelState:
    __slots__ = ()

    def __new__(cls, id: int, pts: int) -> Self: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Any, /) -> bool: ...
    @property
    def id(self) -> int: ...
    @property
    def pts(self) -> int: ...

@final
class UpdatesState(UpdateState):
    __slots__ = ()

    def __new__(
        cls,
        pts: int | UpdateState | UpdatesState = 0,
        qts: int = 0,
        date: int = 0,
        seq: int = 0,
        channels: Sequence[ChannelState] = [],
    ) -> Self: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: Any, /) -> bool: ...
    @property
    def pts(self) -> int: ...
    @pts.setter
    def pts(self, pts: int) -> None: ...
    @property
    def qts(self) -> int: ...
    @qts.setter
    def qts(self, qts: int) -> None: ...
    @property
    def date(self) -> int: ...
    @date.setter
    def date(self, date: int) -> None: ...
    @property
    def seq(self) -> int: ...
    @seq.setter
    def seq(self, seq: int) -> None: ...
    @property
    def channels(self) -> list[ChannelState]: ...
    @channels.setter
    def channels(self, channels: Sequence[ChannelState]) -> None: ...

class UpdateState:
    __slots__ = ()

    All: TypeAlias = UpdatesState

    @final
    class Primary:
        __slots__ = ()

        def __new__(cls, pts: int, date: int, seq: int) -> Self: ...
        def __repr__(self) -> str: ...
        def __eq__(self, other: Any, /) -> bool: ...
        @property
        def pts(self) -> int: ...
        @property
        def date(self) -> int: ...
        @property
        def seq(self) -> int: ...

    @final
    class Secondary:
        __slots__ = ()

        def __new__(cls, qts: int) -> Self: ...
        def __repr__(self) -> str: ...
        def __eq__(self, other: Any, /) -> bool: ...
        @property
        def qts(self) -> int: ...

    @final
    class Channel:
        __slots__ = ()

        def __new__(cls, id: int, pts: int) -> Self: ...
        def __repr__(self) -> str: ...
        def __eq__(self, other: Any, /) -> bool: ...
        @property
        def id(self) -> int: ...
        @property
        def pts(self) -> int: ...

    def __repr__(self) -> str: ...
    def __eq__(self, other: Any, /) -> bool: ...
