[project]
name = "telethon-mtsender"
version = "0.0.1"
authors = [
  { name = "HBcao233", email = "hbcaoqaq@outlook.com" }
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["telegram", "rust", "grammers"]
requires-python = ">=3.9"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = []
optional-dependencies = {}

[project.urls]
Documentation = ""
Homepage = ""
Repository = ""
Issues = ""


[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "telethon_mtsender._rs"
manifest-path = "Cargo.toml"
python-source = "python/"

[tool.pytest.ini_options]
# Only look for tests in these directories.
testpaths = ["python/tests"]

# Exclude path
norecursedirs = [
  ".git",
  "target",
  ".venv",
]
