from typing import final, Self, Optional

@final
class Sender:
    def __new__(
        cls,
        dc_id: int,
        addr: str,
    ) -> Self: ...
    @property
    def dc_id(self) -> int: ...
    @property
    def addr(self) -> str: ...
    @property
    def auth_key(self) -> Optional[bytes]: ...
    async def connect(self, auth_key: Optional[bytes]) -> None: ...
    async def invoke(self, request: bytes) -> bytes: ...
    async def step(self) -> None: ...
    async def disconnect(self) -> None: ...
