from typing import final, Optional, Self

@final
class DroppedError(Exception): ...

@final
class DeserializeError(Exception): ...

@final
class TransportError(Exception): ...

class RpcError(Exception):
    def __new__(
        cls,
        code: int,
        name: str,
        value: Optional[int] = None,
        caused_by: Optional[int] = None,
    ) -> Self: ...
    @property
    def code(self) -> int: ...
    @code.setter
    def code(self, code: int) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str) -> None: ...
    @property
    def value(self) -> Optional[int]: ...
    @value.setter
    def value(self, value: Optional[int]) -> None: ...
    @property
    def caused_by(self) -> Optional[int]: ...
    @caused_by.setter
    def caused_by(self, caused_by: Optional[int]) -> None: ...
    def is_rpc(self, rpc_error: str) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
